/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetChart: typeof import('./src/components/AssetChart.vue')['default']
    AuthButton: typeof import('./src/components/AuthButton.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    DataManager: typeof import('./src/components/DataManager.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    OrderDashboard: typeof import('./src/components/OrderDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartSearch: typeof import('./src/components/SmartSearch.vue')['default']
    TreeItem: typeof import('./src/components/TreeItem.vue')['default']
    UserInfoCard: typeof import('./src/components/UserInfoCard.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
